// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

#ifndef PROTOBUF_INCLUDED_token_2eproto
#define PROTOBUF_INCLUDED_token_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_token_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_token_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_token_2eproto();
namespace PbTokenMsg {
class CreateTokenMsg;
class CreateTokenMsgDefaultTypeInternal;
extern CreateTokenMsgDefaultTypeInternal _CreateTokenMsg_default_instance_;
class LockTokenMsg;
class LockTokenMsgDefaultTypeInternal;
extern LockTokenMsgDefaultTypeInternal _LockTokenMsg_default_instance_;
class TokenMsg;
class TokenMsgDefaultTypeInternal;
extern TokenMsgDefaultTypeInternal _TokenMsg_default_instance_;
class TransferTokenMsg;
class TransferTokenMsgDefaultTypeInternal;
extern TransferTokenMsgDefaultTypeInternal _TransferTokenMsg_default_instance_;
}  // namespace PbTokenMsg
namespace google {
namespace protobuf {
template<> ::PbTokenMsg::CreateTokenMsg* Arena::CreateMaybeMessage<::PbTokenMsg::CreateTokenMsg>(Arena*);
template<> ::PbTokenMsg::LockTokenMsg* Arena::CreateMaybeMessage<::PbTokenMsg::LockTokenMsg>(Arena*);
template<> ::PbTokenMsg::TokenMsg* Arena::CreateMaybeMessage<::PbTokenMsg::TokenMsg>(Arena*);
template<> ::PbTokenMsg::TransferTokenMsg* Arena::CreateMaybeMessage<::PbTokenMsg::TransferTokenMsg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace PbTokenMsg {

// ===================================================================

class TokenMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbTokenMsg.TokenMsg) */ {
 public:
  TokenMsg();
  virtual ~TokenMsg();

  TokenMsg(const TokenMsg& from);

  inline TokenMsg& operator=(const TokenMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TokenMsg(TokenMsg&& from) noexcept
    : TokenMsg() {
    *this = ::std::move(from);
  }

  inline TokenMsg& operator=(TokenMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TokenMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TokenMsg* internal_default_instance() {
    return reinterpret_cast<const TokenMsg*>(
               &_TokenMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TokenMsg* other);
  friend void swap(TokenMsg& a, TokenMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TokenMsg* New() const final {
    return CreateMaybeMessage<TokenMsg>(NULL);
  }

  TokenMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TokenMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TokenMsg& from);
  void MergeFrom(const TokenMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TokenMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 opid = 1;
  bool has_opid() const;
  void clear_opid();
  static const int kOpidFieldNumber = 1;
  ::google::protobuf::uint32 opid() const;
  void set_opid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PbTokenMsg.TokenMsg)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 opid_;
  friend struct ::TableStruct_token_2eproto;
};
// -------------------------------------------------------------------

class CreateTokenMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbTokenMsg.CreateTokenMsg) */ {
 public:
  CreateTokenMsg();
  virtual ~CreateTokenMsg();

  CreateTokenMsg(const CreateTokenMsg& from);

  inline CreateTokenMsg& operator=(const CreateTokenMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateTokenMsg(CreateTokenMsg&& from) noexcept
    : CreateTokenMsg() {
    *this = ::std::move(from);
  }

  inline CreateTokenMsg& operator=(CreateTokenMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CreateTokenMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateTokenMsg* internal_default_instance() {
    return reinterpret_cast<const CreateTokenMsg*>(
               &_CreateTokenMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CreateTokenMsg* other);
  friend void swap(CreateTokenMsg& a, CreateTokenMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateTokenMsg* New() const final {
    return CreateMaybeMessage<CreateTokenMsg>(NULL);
  }

  CreateTokenMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateTokenMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateTokenMsg& from);
  void MergeFrom(const CreateTokenMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateTokenMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string tokenaddress = 2;
  bool has_tokenaddress() const;
  void clear_tokenaddress();
  static const int kTokenaddressFieldNumber = 2;
  const ::std::string& tokenaddress() const;
  void set_tokenaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_tokenaddress(::std::string&& value);
  #endif
  void set_tokenaddress(const char* value);
  void set_tokenaddress(const char* value, size_t size);
  ::std::string* mutable_tokenaddress();
  ::std::string* release_tokenaddress();
  void set_allocated_tokenaddress(::std::string* tokenaddress);

  // required string name = 3;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required string symbol = 4;
  bool has_symbol() const;
  void clear_symbol();
  static const int kSymbolFieldNumber = 4;
  const ::std::string& symbol() const;
  void set_symbol(const ::std::string& value);
  #if LANG_CXX11
  void set_symbol(::std::string&& value);
  #endif
  void set_symbol(const char* value);
  void set_symbol(const char* value, size_t size);
  ::std::string* mutable_symbol();
  ::std::string* release_symbol();
  void set_allocated_symbol(::std::string* symbol);

  // required uint32 opid = 1;
  bool has_opid() const;
  void clear_opid();
  static const int kOpidFieldNumber = 1;
  ::google::protobuf::uint32 opid() const;
  void set_opid(::google::protobuf::uint32 value);

  // required uint32 digits = 6;
  bool has_digits() const;
  void clear_digits();
  static const int kDigitsFieldNumber = 6;
  ::google::protobuf::uint32 digits() const;
  void set_digits(::google::protobuf::uint32 value);

  // required uint64 totalamount = 5;
  bool has_totalamount() const;
  void clear_totalamount();
  static const int kTotalamountFieldNumber = 5;
  ::google::protobuf::uint64 totalamount() const;
  void set_totalamount(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:PbTokenMsg.CreateTokenMsg)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr tokenaddress_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr symbol_;
  ::google::protobuf::uint32 opid_;
  ::google::protobuf::uint32 digits_;
  ::google::protobuf::uint64 totalamount_;
  friend struct ::TableStruct_token_2eproto;
};
// -------------------------------------------------------------------

class TransferTokenMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbTokenMsg.TransferTokenMsg) */ {
 public:
  TransferTokenMsg();
  virtual ~TransferTokenMsg();

  TransferTokenMsg(const TransferTokenMsg& from);

  inline TransferTokenMsg& operator=(const TransferTokenMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TransferTokenMsg(TransferTokenMsg&& from) noexcept
    : TransferTokenMsg() {
    *this = ::std::move(from);
  }

  inline TransferTokenMsg& operator=(TransferTokenMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TransferTokenMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TransferTokenMsg* internal_default_instance() {
    return reinterpret_cast<const TransferTokenMsg*>(
               &_TransferTokenMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(TransferTokenMsg* other);
  friend void swap(TransferTokenMsg& a, TransferTokenMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TransferTokenMsg* New() const final {
    return CreateMaybeMessage<TransferTokenMsg>(NULL);
  }

  TransferTokenMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TransferTokenMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TransferTokenMsg& from);
  void MergeFrom(const TransferTokenMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransferTokenMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string dstAddress = 2;
  bool has_dstaddress() const;
  void clear_dstaddress();
  static const int kDstAddressFieldNumber = 2;
  const ::std::string& dstaddress() const;
  void set_dstaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_dstaddress(::std::string&& value);
  #endif
  void set_dstaddress(const char* value);
  void set_dstaddress(const char* value, size_t size);
  ::std::string* mutable_dstaddress();
  ::std::string* release_dstaddress();
  void set_allocated_dstaddress(::std::string* dstaddress);

  // required string comment = 5;
  bool has_comment() const;
  void clear_comment();
  static const int kCommentFieldNumber = 5;
  const ::std::string& comment() const;
  void set_comment(const ::std::string& value);
  #if LANG_CXX11
  void set_comment(::std::string&& value);
  #endif
  void set_comment(const char* value);
  void set_comment(const char* value, size_t size);
  ::std::string* mutable_comment();
  ::std::string* release_comment();
  void set_allocated_comment(::std::string* comment);

  // required uint32 opid = 1;
  bool has_opid() const;
  void clear_opid();
  static const int kOpidFieldNumber = 1;
  ::google::protobuf::uint32 opid() const;
  void set_opid(::google::protobuf::uint32 value);

  // required uint32 tokenid = 3;
  bool has_tokenid() const;
  void clear_tokenid();
  static const int kTokenidFieldNumber = 3;
  ::google::protobuf::uint32 tokenid() const;
  void set_tokenid(::google::protobuf::uint32 value);

  // required uint64 amount = 4;
  bool has_amount() const;
  void clear_amount();
  static const int kAmountFieldNumber = 4;
  ::google::protobuf::uint64 amount() const;
  void set_amount(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:PbTokenMsg.TransferTokenMsg)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr dstaddress_;
  ::google::protobuf::internal::ArenaStringPtr comment_;
  ::google::protobuf::uint32 opid_;
  ::google::protobuf::uint32 tokenid_;
  ::google::protobuf::uint64 amount_;
  friend struct ::TableStruct_token_2eproto;
};
// -------------------------------------------------------------------

class LockTokenMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PbTokenMsg.LockTokenMsg) */ {
 public:
  LockTokenMsg();
  virtual ~LockTokenMsg();

  LockTokenMsg(const LockTokenMsg& from);

  inline LockTokenMsg& operator=(const LockTokenMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LockTokenMsg(LockTokenMsg&& from) noexcept
    : LockTokenMsg() {
    *this = ::std::move(from);
  }

  inline LockTokenMsg& operator=(LockTokenMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LockTokenMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LockTokenMsg* internal_default_instance() {
    return reinterpret_cast<const LockTokenMsg*>(
               &_LockTokenMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(LockTokenMsg* other);
  friend void swap(LockTokenMsg& a, LockTokenMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LockTokenMsg* New() const final {
    return CreateMaybeMessage<LockTokenMsg>(NULL);
  }

  LockTokenMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LockTokenMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LockTokenMsg& from);
  void MergeFrom(const LockTokenMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LockTokenMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string dstAddress = 2;
  bool has_dstaddress() const;
  void clear_dstaddress();
  static const int kDstAddressFieldNumber = 2;
  const ::std::string& dstaddress() const;
  void set_dstaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_dstaddress(::std::string&& value);
  #endif
  void set_dstaddress(const char* value);
  void set_dstaddress(const char* value, size_t size);
  ::std::string* mutable_dstaddress();
  ::std::string* release_dstaddress();
  void set_allocated_dstaddress(::std::string* dstaddress);

  // required string comment = 5;
  bool has_comment() const;
  void clear_comment();
  static const int kCommentFieldNumber = 5;
  const ::std::string& comment() const;
  void set_comment(const ::std::string& value);
  #if LANG_CXX11
  void set_comment(::std::string&& value);
  #endif
  void set_comment(const char* value);
  void set_comment(const char* value, size_t size);
  ::std::string* mutable_comment();
  ::std::string* release_comment();
  void set_allocated_comment(::std::string* comment);

  // required uint32 opid = 1;
  bool has_opid() const;
  void clear_opid();
  static const int kOpidFieldNumber = 1;
  ::google::protobuf::uint32 opid() const;
  void set_opid(::google::protobuf::uint32 value);

  // required uint32 tokenid = 3;
  bool has_tokenid() const;
  void clear_tokenid();
  static const int kTokenidFieldNumber = 3;
  ::google::protobuf::uint32 tokenid() const;
  void set_tokenid(::google::protobuf::uint32 value);

  // required uint64 amount = 4;
  bool has_amount() const;
  void clear_amount();
  static const int kAmountFieldNumber = 4;
  ::google::protobuf::uint64 amount() const;
  void set_amount(::google::protobuf::uint64 value);

  // required uint64 expiryheight = 6;
  bool has_expiryheight() const;
  void clear_expiryheight();
  static const int kExpiryheightFieldNumber = 6;
  ::google::protobuf::uint64 expiryheight() const;
  void set_expiryheight(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:PbTokenMsg.LockTokenMsg)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr dstaddress_;
  ::google::protobuf::internal::ArenaStringPtr comment_;
  ::google::protobuf::uint32 opid_;
  ::google::protobuf::uint32 tokenid_;
  ::google::protobuf::uint64 amount_;
  ::google::protobuf::uint64 expiryheight_;
  friend struct ::TableStruct_token_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TokenMsg

// required uint32 opid = 1;
inline bool TokenMsg::has_opid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TokenMsg::clear_opid() {
  opid_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint32 TokenMsg::opid() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.TokenMsg.opid)
  return opid_;
}
inline void TokenMsg::set_opid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  opid_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.TokenMsg.opid)
}

// -------------------------------------------------------------------

// CreateTokenMsg

// required uint32 opid = 1;
inline bool CreateTokenMsg::has_opid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CreateTokenMsg::clear_opid() {
  opid_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint32 CreateTokenMsg::opid() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.CreateTokenMsg.opid)
  return opid_;
}
inline void CreateTokenMsg::set_opid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  opid_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.CreateTokenMsg.opid)
}

// required string tokenaddress = 2;
inline bool CreateTokenMsg::has_tokenaddress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateTokenMsg::clear_tokenaddress() {
  tokenaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& CreateTokenMsg::tokenaddress() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.CreateTokenMsg.tokenaddress)
  return tokenaddress_.GetNoArena();
}
inline void CreateTokenMsg::set_tokenaddress(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  tokenaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.CreateTokenMsg.tokenaddress)
}
#if LANG_CXX11
inline void CreateTokenMsg::set_tokenaddress(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  tokenaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.CreateTokenMsg.tokenaddress)
}
#endif
inline void CreateTokenMsg::set_tokenaddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000001u;
  tokenaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.CreateTokenMsg.tokenaddress)
}
inline void CreateTokenMsg::set_tokenaddress(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  tokenaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.CreateTokenMsg.tokenaddress)
}
inline ::std::string* CreateTokenMsg::mutable_tokenaddress() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.CreateTokenMsg.tokenaddress)
  return tokenaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateTokenMsg::release_tokenaddress() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.CreateTokenMsg.tokenaddress)
  if (!has_tokenaddress()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000001u;
  return tokenaddress_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateTokenMsg::set_allocated_tokenaddress(::std::string* tokenaddress) {
  if (tokenaddress != NULL) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  tokenaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tokenaddress);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.CreateTokenMsg.tokenaddress)
}

// required string name = 3;
inline bool CreateTokenMsg::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateTokenMsg::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& CreateTokenMsg::name() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.CreateTokenMsg.name)
  return name_.GetNoArena();
}
inline void CreateTokenMsg::set_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.CreateTokenMsg.name)
}
#if LANG_CXX11
inline void CreateTokenMsg::set_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.CreateTokenMsg.name)
}
#endif
inline void CreateTokenMsg::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.CreateTokenMsg.name)
}
inline void CreateTokenMsg::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.CreateTokenMsg.name)
}
inline ::std::string* CreateTokenMsg::mutable_name() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.CreateTokenMsg.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateTokenMsg::release_name() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.CreateTokenMsg.name)
  if (!has_name()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000002u;
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateTokenMsg::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.CreateTokenMsg.name)
}

// required string symbol = 4;
inline bool CreateTokenMsg::has_symbol() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CreateTokenMsg::clear_symbol() {
  symbol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& CreateTokenMsg::symbol() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.CreateTokenMsg.symbol)
  return symbol_.GetNoArena();
}
inline void CreateTokenMsg::set_symbol(const ::std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.CreateTokenMsg.symbol)
}
#if LANG_CXX11
inline void CreateTokenMsg::set_symbol(::std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  symbol_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.CreateTokenMsg.symbol)
}
#endif
inline void CreateTokenMsg::set_symbol(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000004u;
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.CreateTokenMsg.symbol)
}
inline void CreateTokenMsg::set_symbol(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.CreateTokenMsg.symbol)
}
inline ::std::string* CreateTokenMsg::mutable_symbol() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.CreateTokenMsg.symbol)
  return symbol_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateTokenMsg::release_symbol() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.CreateTokenMsg.symbol)
  if (!has_symbol()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000004u;
  return symbol_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateTokenMsg::set_allocated_symbol(::std::string* symbol) {
  if (symbol != NULL) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  symbol_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), symbol);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.CreateTokenMsg.symbol)
}

// required uint64 totalamount = 5;
inline bool CreateTokenMsg::has_totalamount() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CreateTokenMsg::clear_totalamount() {
  totalamount_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::uint64 CreateTokenMsg::totalamount() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.CreateTokenMsg.totalamount)
  return totalamount_;
}
inline void CreateTokenMsg::set_totalamount(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  totalamount_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.CreateTokenMsg.totalamount)
}

// required uint32 digits = 6;
inline bool CreateTokenMsg::has_digits() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CreateTokenMsg::clear_digits() {
  digits_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::uint32 CreateTokenMsg::digits() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.CreateTokenMsg.digits)
  return digits_;
}
inline void CreateTokenMsg::set_digits(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  digits_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.CreateTokenMsg.digits)
}

// -------------------------------------------------------------------

// TransferTokenMsg

// required uint32 opid = 1;
inline bool TransferTokenMsg::has_opid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TransferTokenMsg::clear_opid() {
  opid_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::uint32 TransferTokenMsg::opid() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.TransferTokenMsg.opid)
  return opid_;
}
inline void TransferTokenMsg::set_opid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  opid_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.TransferTokenMsg.opid)
}

// required string dstAddress = 2;
inline bool TransferTokenMsg::has_dstaddress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TransferTokenMsg::clear_dstaddress() {
  dstaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& TransferTokenMsg::dstaddress() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.TransferTokenMsg.dstAddress)
  return dstaddress_.GetNoArena();
}
inline void TransferTokenMsg::set_dstaddress(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.TransferTokenMsg.dstAddress)
}
#if LANG_CXX11
inline void TransferTokenMsg::set_dstaddress(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.TransferTokenMsg.dstAddress)
}
#endif
inline void TransferTokenMsg::set_dstaddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.TransferTokenMsg.dstAddress)
}
inline void TransferTokenMsg::set_dstaddress(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.TransferTokenMsg.dstAddress)
}
inline ::std::string* TransferTokenMsg::mutable_dstaddress() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.TransferTokenMsg.dstAddress)
  return dstaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TransferTokenMsg::release_dstaddress() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.TransferTokenMsg.dstAddress)
  if (!has_dstaddress()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000001u;
  return dstaddress_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TransferTokenMsg::set_allocated_dstaddress(::std::string* dstaddress) {
  if (dstaddress != NULL) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  dstaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dstaddress);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.TransferTokenMsg.dstAddress)
}

// required uint32 tokenid = 3;
inline bool TransferTokenMsg::has_tokenid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TransferTokenMsg::clear_tokenid() {
  tokenid_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint32 TransferTokenMsg::tokenid() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.TransferTokenMsg.tokenid)
  return tokenid_;
}
inline void TransferTokenMsg::set_tokenid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  tokenid_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.TransferTokenMsg.tokenid)
}

// required uint64 amount = 4;
inline bool TransferTokenMsg::has_amount() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TransferTokenMsg::clear_amount() {
  amount_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::uint64 TransferTokenMsg::amount() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.TransferTokenMsg.amount)
  return amount_;
}
inline void TransferTokenMsg::set_amount(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  amount_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.TransferTokenMsg.amount)
}

// required string comment = 5;
inline bool TransferTokenMsg::has_comment() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TransferTokenMsg::clear_comment() {
  comment_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& TransferTokenMsg::comment() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.TransferTokenMsg.comment)
  return comment_.GetNoArena();
}
inline void TransferTokenMsg::set_comment(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.TransferTokenMsg.comment)
}
#if LANG_CXX11
inline void TransferTokenMsg::set_comment(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.TransferTokenMsg.comment)
}
#endif
inline void TransferTokenMsg::set_comment(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.TransferTokenMsg.comment)
}
inline void TransferTokenMsg::set_comment(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.TransferTokenMsg.comment)
}
inline ::std::string* TransferTokenMsg::mutable_comment() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.TransferTokenMsg.comment)
  return comment_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TransferTokenMsg::release_comment() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.TransferTokenMsg.comment)
  if (!has_comment()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000002u;
  return comment_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TransferTokenMsg::set_allocated_comment(::std::string* comment) {
  if (comment != NULL) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  comment_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), comment);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.TransferTokenMsg.comment)
}

// -------------------------------------------------------------------

// LockTokenMsg

// required uint32 opid = 1;
inline bool LockTokenMsg::has_opid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LockTokenMsg::clear_opid() {
  opid_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::uint32 LockTokenMsg::opid() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.LockTokenMsg.opid)
  return opid_;
}
inline void LockTokenMsg::set_opid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  opid_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.LockTokenMsg.opid)
}

// required string dstAddress = 2;
inline bool LockTokenMsg::has_dstaddress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LockTokenMsg::clear_dstaddress() {
  dstaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& LockTokenMsg::dstaddress() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.LockTokenMsg.dstAddress)
  return dstaddress_.GetNoArena();
}
inline void LockTokenMsg::set_dstaddress(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.LockTokenMsg.dstAddress)
}
#if LANG_CXX11
inline void LockTokenMsg::set_dstaddress(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.LockTokenMsg.dstAddress)
}
#endif
inline void LockTokenMsg::set_dstaddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.LockTokenMsg.dstAddress)
}
inline void LockTokenMsg::set_dstaddress(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  dstaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.LockTokenMsg.dstAddress)
}
inline ::std::string* LockTokenMsg::mutable_dstaddress() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.LockTokenMsg.dstAddress)
  return dstaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LockTokenMsg::release_dstaddress() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.LockTokenMsg.dstAddress)
  if (!has_dstaddress()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000001u;
  return dstaddress_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LockTokenMsg::set_allocated_dstaddress(::std::string* dstaddress) {
  if (dstaddress != NULL) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  dstaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dstaddress);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.LockTokenMsg.dstAddress)
}

// required uint32 tokenid = 3;
inline bool LockTokenMsg::has_tokenid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LockTokenMsg::clear_tokenid() {
  tokenid_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::uint32 LockTokenMsg::tokenid() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.LockTokenMsg.tokenid)
  return tokenid_;
}
inline void LockTokenMsg::set_tokenid(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  tokenid_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.LockTokenMsg.tokenid)
}

// required uint64 amount = 4;
inline bool LockTokenMsg::has_amount() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LockTokenMsg::clear_amount() {
  amount_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::uint64 LockTokenMsg::amount() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.LockTokenMsg.amount)
  return amount_;
}
inline void LockTokenMsg::set_amount(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  amount_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.LockTokenMsg.amount)
}

// required string comment = 5;
inline bool LockTokenMsg::has_comment() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LockTokenMsg::clear_comment() {
  comment_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& LockTokenMsg::comment() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.LockTokenMsg.comment)
  return comment_.GetNoArena();
}
inline void LockTokenMsg::set_comment(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PbTokenMsg.LockTokenMsg.comment)
}
#if LANG_CXX11
inline void LockTokenMsg::set_comment(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PbTokenMsg.LockTokenMsg.comment)
}
#endif
inline void LockTokenMsg::set_comment(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PbTokenMsg.LockTokenMsg.comment)
}
inline void LockTokenMsg::set_comment(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PbTokenMsg.LockTokenMsg.comment)
}
inline ::std::string* LockTokenMsg::mutable_comment() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:PbTokenMsg.LockTokenMsg.comment)
  return comment_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LockTokenMsg::release_comment() {
  // @@protoc_insertion_point(field_release:PbTokenMsg.LockTokenMsg.comment)
  if (!has_comment()) {
    return NULL;
  }
  _has_bits_[0] &= ~0x00000002u;
  return comment_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LockTokenMsg::set_allocated_comment(::std::string* comment) {
  if (comment != NULL) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  comment_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), comment);
  // @@protoc_insertion_point(field_set_allocated:PbTokenMsg.LockTokenMsg.comment)
}

// required uint64 expiryheight = 6;
inline bool LockTokenMsg::has_expiryheight() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LockTokenMsg::clear_expiryheight() {
  expiryheight_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::uint64 LockTokenMsg::expiryheight() const {
  // @@protoc_insertion_point(field_get:PbTokenMsg.LockTokenMsg.expiryheight)
  return expiryheight_;
}
inline void LockTokenMsg::set_expiryheight(::google::protobuf::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  expiryheight_ = value;
  // @@protoc_insertion_point(field_set:PbTokenMsg.LockTokenMsg.expiryheight)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PbTokenMsg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_token_2eproto
